apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sample-app
spec:
  selector:
    matchLabels:
      app: flask-sample-app
  template:
    metadata:
      labels:
        app: flask-sample-app
    spec:
      containers:
      - name: flask-sample-app
        image: guisilveira/flask-sample-app:{{tag}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-sample-app-service
spec:
  selector:
    app: flask-sample-app
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-sample-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: flask.silveira.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flask-sample-app-service
            port: 
              number: 5000


